spring:
  application:
    name: Chapter20
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beginner?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: beginner_user
    password: beginner1234@

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.gamecrud
configuration:
  map-underscore-to-camel-case: true